
services:
  tutorlink-backend:
    build: .
    container_name: tutorlink-backend
    ports:
      - '11000:11000'
    command: npm run dev
    environment:
      - MONGO_URL=mongodb://localhost:27017/TutorLink

    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

